# Threadpools categorization and configuration of Thread Dumps

pools:
  # Disruptor Based Flusher Threadpool
  - name: "DisruptorBasedFlusher"
    patterns:
      - "^DisruptorBasedFlusher-\\d+$"

  # http-nio- Threadpool
  - name: "Tomcat HTTP Threads"
    patterns:
      - "^http-nio-\\d+-exec-\\d+$"

  # https-jsse-nio- Threadpool
  - name: "Tomcat HTTPS Threads"
    patterns:
      - "^https-jsse-nio-\\d+-exec-\\d+$"

  # Worker Threads Threadpool
  - name: "Worker Threads"
    patterns:
      - "^pool-\\d+-thread-\\d+$"

  # JobPoolThread Threadpool
  - name: "JobPool Threads"
    patterns:
      - "^JobPoolThread-\\d+$"

  # CacheExpiryScheduler Threadpool
  - name: "CacheExpiryScheduler"
    patterns:
      - "^CacheExpirySchedulerThread-\\d+$"

  # DisruptorInboundEvent Threadpool
  - name: "DisruptorInboundEvent"
    patterns:
      - "^DisruptorInboundEventThread-\\d+$"

  # Mina Network Transport Threadpool
  - name: "Mina Network Transport"
    patterns:
      - "^MinaNetworkTransport\\(Acceptor\\)-\\d+$"
      - "^MinaNetworkTransport\\(Client\\)-\\d+$"

  # PassThroughMessageProcessor Threadpool
  - name: "PassThroughMessageProcessor Threads"
    patterns:
      - "^PassThroughMessageProcessor-\\d+$"

  # SynapseWorker Threadpool
  - name: "SynapseWorker Threads"
    patterns:
      - "^SynapseWorker-\\d+$"

  # DisruptorInboundEvent Threadpool
  - name: "DisruptorInboundEvent Threads"
    patterns:
      - "^DisruptorInboundEventThread-\\d+$"

  # DataBridge Threadpools

  # DataBridge Core pool Threadpool
  - name: "DataBridge Core Threads"
    patterns:
      - "^DataBridge-Core-pool-\\d+-thread-\\d+$"

  # DataBridge Receiver Binary SSL Threadpool
  - name: "DataBridge Receiver Binary (SSL Threads)"
    patterns:
      - "^DataBridge-Receiver-Binary-SSL-pool-\\d+-thread-\\d+$"

  # DataBridge Receiver Binary TCP Threadpool
  - name: "DataBridge Receiver Binary (TCP Threads)"
    patterns:
      - "^DataBridge-Receiver-Binary-TCP-pool-\\d+-thread-\\d+$"

  # HTTP-Listener I/O Dispatcher Threadpool
  - name: "HTTP-Listener I/O Dispatcher Threads"
    patterns:
      - "^HTTP-Listener I/O dispatcher-\\d+$"

  # HTTPS-Listener I/O Dispatcher Threadpool
  - name: "HTTPS-Listener I/O Dispatcher Threads"
    patterns:
      - "^HTTPS-Listener I/O dispatcher-\\d+$"

  # HTTP-Sender I/O Dispatcher Threadpool
  - name: "HTTP-Sender I/O Dispatcher Threads"
    patterns:
      - "^HTTP-Sender I/O dispatcher-\\d+$"

  # HTTPS-Sender I/O Dispatcher Threadpool
  - name: "HTTPS-Sender I/O Dispatcher Threads"
    patterns:
      - "^HTTPS-Sender I/O dispatcher-\\d+$"
