# Threadpools categorization and configuration of Thread Dumps

pools:
  # Disruptor Based Flusher Threadpool
  - name: "DisruptorBasedFlusher"
    patterns:
      - "^DisruptorBasedFlusher-\\d+$"

  # http-nio- Threadpool
  - name: "Tomcat HTTP Threads"
    patterns:
      - "^http-nio-\\d+-exec-\\d+$"

  # https-jsse-nio- Threadpool
  - name: "Tomcat HTTPS Threads"
    patterns:
      - "^https-jsse-nio-\\d+-exec-\\d+$"

  # Worker Threads Threadpool
  - name: "Worker Threads"
    patterns:
      - "^pool-\\d+-thread-\\d+$"

  # JobPoolThread Threadpool
  - name: "JobPool Threads"
    patterns:
      - "^JobPoolThread-\\d+$"

  # Databridge Core pool Threadpool
  - name: "Databridge Core Threads"
    patterns:
      - "^Databridge-Core-pool-\\d+-thread-\\d+$"

  # CacheExpiryScheduler Threadpool
  - name: "CacheExpiryScheduler"
    patterns:
      - "^CacheExpirySchedulerThread-\\d+$"

  # DisruptorInboundEvent Threadpool
  - name: "DisruptorInboundEvent"
    patterns:
      - "^DisruptorInboundEventThread-\\d+$"

  # Mina Network Transport Threadpool
  - name: "Mina Network Transport"
    patterns:
      - "^MinaNetworkTransport\\(Acceptor\\)-\\d+$"
      - "^MinaNetworkTransport\\(Client\\)-\\d+$"

  # PassThroughMessageProcessor Threadpool
  - name: "PassThroughMessageProcessor Threads"
    patterns:
      - "^PassThroughMessageProcessor-\\d+$"

  #SynapseWorker Threadpool
  - name: "SynapseWorker Threads"
    patterns:
      - "^SynapseWorker-\\d+$"

  #DisruptorInboundEvent Threadpool
  - name: "DisruptorInboundEvent Threads"
    patterns:
      - "^DisruptorInboundEventThread-\\d+$"

  #DataBridge Core Threadpool
  - name: "DataBridge Core Threads"
    patterns:
      - "DataBridge-Core-pool-\\d+-thread-\\d+$"